### ISSUE TITLE
AWS Provider 'Region" Argument Converted to Read-Only Attribute

### ISSUE THREAD

**Issue by jakeasarus** [thinkstack-co/terraform-modules#19]
### Region No Longer S3 Argument
Region no longer an argument of the s3 bucket resource as of version 3.0.0 of the Terraform AWS provider. 

**AWS Provider Changelog**
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md
 
**Commit #14127**
https://github.com/terraform-providers/terraform-provider-aws/pull/14127

**What this Means**
**You will see errors like this when your plan runs**
![image](https://user-images.githubusercontent.com/47454060/89186136-5f936900-d569-11ea-9056-e6b3f3f70906.png)

**These errors can be fixed by removing this argument from your code**
`region        = var.aws_region`

**Impacted Modules**
1. S3 Modules
2. Cloudtrail Modules

**Next Steps:**
- [ ] Create issue in terraform-modules
- [ ] Remove region argument from S3 module in terraform-modules
- [ ] Remove var.region variable from S3 module in terraform-modules
- [ ] Check to see if region argument and variable need to be removed from the cloudtrail module

**Comment by tgallagher91** [comment]
published new branch and pull request to resolve.

**Comment by tgallagher91** [comment]
issue resolved by removing region arguments and variables from s3 and cloudtrail modules.
