### ISSUE TITLE
AWS_Route Modules failing on newer AWS Provider versions.

### ISSUE THREAD

**Issue by tgallagher91** [thinkstack-co/terraform-modules#36]
### Describe the bug
When running a terraform plan on the newest AWS provider, you will receive an "Error: ExactlyOne" output from terraform. Screenshot below.

![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/63355740/113726493-49264a00-96c2-11eb-8427-2494c0238d50.png)

### To Reproduce

Example Code:

1. Set remove hard coded version from O'Leary Prod Infrastructure code
2. save and commit
3. run a terraform plan

### Expected behavior
Expected behavior is for the code to work as it had before, producing no ExactlyOne error.

### Problems
There is likely something wrong with the inputs we have selected for the module, or something of that sort.

### Next Steps
Meet with CCoE during L10 and discuss as an issue.

**Comment by zachreborn** [comment]
Created the following pull request to resolve this.

https://github.com/thinkstack-co/terraform-modules/pull/37

**Comment by zachreborn** [comment]
The primary issue is that `default = "" ` was being utilized which matched v0.11 methods. Transitioning the aws_route module to `default = null`.

Some tweaks needed to be made to the network_interface_id variable to match. This has been tested on VPN peer routes. Need to test it on a route that points to the network_interface_id for a fortigate firewall

**Comment by jakeasarus** [comment]
Tested a run with this in Liberty and ran into additional errors. 

Example code for one of the modules:
module "route_199_186_96_0" {
  source = "github.com/thinkstack-co/terraform-modules//modules/aws/route?ref=dev_aws_route_provider_v3.35.0"

  network_interface_id   = module.aws_prod_fw.private_network_interface_id[0]
  route_table_id         = module.vpc.private_route_table_ids
  destination_cidr_block = "199.186.96.0/24"
}

[Link to run](https://app.terraform.io/app/thinkstack-co/workspaces/liberty_prod_infrastructure/runs/run-SVKNd6Rp6NZFa8aq)

**Comment by zachreborn** [comment]
I see you found your problem, it looks all good yeah?

**Comment by jakeasarus** [comment]
Maybe. I think in your PR to fix we need to either remove the arguments that are not expected, but what is weird is that they are valid arguments for the routes module in terraform documentation. 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route

My thought is that maybe it wants only one and even having 'null' gives it a value and upsets terraform.

**Comment by zachreborn** [comment]
Review and tests show that this is corrected. Merging up.
